"""update basemodel

Revision ID: 1cdc3936cc5c
Revises: 
Create Date: 2025-01-16 16:07:45.305488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cdc3936cc5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('customer_contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('expense_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('income_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('product_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('vendor_contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('vendor_contacts', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('product_services', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('income_category', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('expense_category', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('customer_contacts', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
